### ISSUE TITLE
@ignoreupstream ineffective on big query view

### ISSUE THREAD

**Issue by SumitAgrawal03071989** [odpf/transformers#11]
We have a query referencing to table as well as view. 
`select * 
from proj.dataset.table t1
left join proj.dataset.view v1 
on t1.date = v1.date and t1.id = v1.id`
* now if we apply @ignoreupstream helper on table `proj.dataset.table` then it correctly ignores to create upstream dependancy for this table.
* But if we apply @ignoreupstream helper on view `proj.dataset.view` ( note the view query refers to 2 more tables ) then it does not ignore view or table referenced by view.

**Comment by ravisuhag** [comment]
@SumitAgrawal03071989 Can you state the reason to close this?

**Comment by SumitAgrawal03071989** [comment]
This issue is not required as its getting tackled by [this](https://github.com/odpf/optimus/issues/131) feature in core optimus.
For reference adding the [PR](https://github.com/odpf/transformers/pull/12) with detailes of it.
